terminologyList={'acil': 'emergency',
 'acil dur': 'emergency',
 'Acil Servis': 'A&E',
 'aç karn': 'on an empty stomach',
 'adele yırtılma': 'muscle tear',
 'adet ağr': 'period pain',
 'adet olmak': 'have a period',
 'Afrika kökenli Karayipli': 'African Caribbean',
 'aft': 'mouth ulcer',
 'ağır akut solunum yetersizliği sendrom': 'severe acute respiratory syndrome',
 'ağız koku': 'bad breath',
 'ağız kuruluk': 'dry mouth',
 'Ağız ve Diş Hastalıkları': 'Oral and Dental Diseases',
 'ağrı kesiç': 'painkiller',
 'ağrıyı dindirmek': 'dull the pain',
 'aile hek': 'GP',
 'akciğer kanser': 'lung cancer',
 'akciğer sertleşme': 'idiopathic pulmonary fibrosis',
 'akciğer zarı iltihap': 'pleurisy',
 'Akdeniz anemi': 'thalassaemia',
 'akupunk': 'acupuncture',
 'akut': 'acute',
 'akyuvar': 'white blood cells',
 'ala hastalık': 'vitiligo',
 'alç': 'cast',
 'alerj': 'allergy',
 'alerjik reaksiyon': 'allergic reaction',
 'alyuvar': 'red blood cells',
 'ameliyat': 'surgical operation',
 'ameliyat edilmesi mümkün olmayan': 'inoperable',
 'ameliyat etmek': 'operate',
 'ameliyathane': 'operating theatre',
 'Amerika Hastalık Kontrol Merkezi': 'Center for Disease Control (CDC)',
 'ana çocuk sağlık': 'maternal and infant health',
 'anafilaksi': 'anaphylaxis',
 'analjezik': 'analgesics',
 'anestezist': 'anaesthetist',
 'anestezi uzman': 'anesthesiologist',
 'Anestezi ve Reanimasyon': 'Anesthesiology and Reanimation',
 'ani bebek ölümü sendrom': 'sudden infant death syndrome',
 'anjiyoplasti': 'angioplasty',
 'anksiye': 'anxiety',
 'anksiyete bozukluk': 'anxiety disorder',
 'anne aday': 'expectant mother',
 'anoreksiya nervoz': 'anorexia nervosa',
 'anti-koagülatör': 'anti-coagulants',
 'anti-psikotikler': 'antipsychotics',
 'antibakteriyel': 'antibacterials',
 'antibiyotik': 'antibiotics',
 'antidiyabe': 'antidiabetic',
 'antie': 'antiemetics',
 'antienflamatuar': 'anti-inflammatories',
 'antijen': 'antigen',
 'antikonvülsan': 'anticonvulsants',
 'antikor': 'antibody',
 'antiromatik': 'antirheumetic',
 'antisep': 'antiseptic',
 'antiviraller': 'antivirals',
 'aort damarı (şahdamar)': 'aorta',
 'apandisit': 'appendicitis',
 'apse': 'abscess',
 'araz': 'symptom',
 'artrit': 'arthritis',
 'asbest': 'asbestos',
 'asemptomatik (belirti göstermeyen)': 'asymptomatic',
 'aş': 'vaccination',
 'aşı karş': 'anti-vaccination',
 'aşı karşıt': 'anti-vaxxers',
 'aşı tereddü': 'vaccine hesitancy',
 'aşı zorunluluk': 'vaccine mandate',
 'aşılan': 'vaccine uptake',
 'aşındırıç': 'corrosive',
 'aşırı savunmas': 'clinically vulnerable',
 'aşırı terl': 'hyperhidrosis',
 'aşırı yem': 'binge eating',
 'ast': 'asthma',
 'atel': 'splint',
 'ateş': 'fever',
 'ateş düşürüç': 'antifebrile',
 'ateşi olmak': 'have a temperature',
 'ateşli bağırsak rahatsızlığı ajan': 'inflammatory bowel disease agents',
 'ateşli havale': 'febrile seizures',
 'atlet ayak': "athlete's foot",
 'ayak mantar': "athlete's foot",
 'ayakta tedavi': 'outpatient care',
 'ayaktan bak': 'walk-in surgery',
 'azı diş': 'molar',
 'bademcik iltihap': 'tonsillitis',
 'bağımlılığı birden bırakmak': 'go cold turkey',
 'bağırsak kanser': 'bowel cancer',
 'bağışıklığı baskılan': 'immunocompromised',
 'bağışıklık bil': 'immunology',
 'bağışıklık sistemini baskılayıç': 'immunosuppressant',
 'balg': 'phlegm',
 'balgam söktürüç': 'expectorant',
 'bal': 'calf',
 'bandaj': 'bandage',
 'baş ağr': 'headache',
 'baş dönm': 'dizziness',
 'baş-boyun kanser': 'head and neck cancer',
 'baskılayıç': 'suppressant',
 'basur': 'piles',
 'Batı Nil Virüsü': 'West Nile Virus',
 'batık tırnak': 'ingrown toenail',
 'BCG aşıs': 'BCG vaccination',
 'bel ağr': 'backache',
 'belir': 'symptom',
 'belirtis': 'asymptomatic',
 'belsoğukluk': 'gonorrhoea',
 'beşinci hastalık': 'slapped cheek',
 'beslenme ve diyet': 'nutrition and diet',
 'beyaz kod': 'code white',
 'beyin felç': 'cerebral palsy',
 'beyin kana': 'cerebral haemorrhage',
 'beyin sap': 'brain stem',
 'beyin sis': 'brain fog',
 'bez maske': 'cloth mask',
 'bıngıldak': 'fontanelle',
 'bildirimi zorunlu hastalık': 'notifiable diseases',
 'bilgisayarlı tomografi': 'computed tomography',
 'bilinci açık': 'alert',
 'bilinci kap': 'unresponsive',
 'bipolar bozukluk': 'bipolar disorder',
 'birinci basamak sağlık hizm': 'primary care',
 'birincil vak': 'primary case',
 'bitlenmek': 'infested with head lice',
 'biyobelirteç': 'biomarker',
 'biyobenzer': 'biosimilar',
 'biyokimya uzmanlık': 'biochemistry',
 'böbrek taş': 'kidney stone',
 'boğaz ağr': 'sore throat',
 'boğm': 'pertussis (whooping cough)',
 'bozukluk': 'disorder',
 'bronşektazi': 'bronchiectasis',
 'bronşit': 'bronchitis',
 'BT incele': 'CT scan',
 'bulanık görm': 'amblyopia',
 'bulaş': 'infection',
 'bulaşma katsa': 'R number',
 'bulimia': 'bulimia',
 'bun': 'dementia',
 'bunyon': 'bunion',
 'burun akın': 'runny nose',
 'burun kana': 'nosebleed',
 'büyük abdest': 'stool',
 'cen': 'foetus',
 'cerahat': 'pus',
 'cerrah': 'surgeon',
 'cerrahi maske': 'surgical mask',
 'cıv': 'mercury',
 'cilt': 'dermatology',
 'cilt kanser': 'skin cancer',
 'cilt yang': 'dermatitis',
 'Creutzfeldt-Jakob hastalık': 'Creutzfeldt-Jakob disease',
 'Crohn hastalık': "Crohn's disease",
 'cüzzam': 'leper',
 'çare': 'remedy',
 'çekiç kemik': 'malleus',
 'çıban': 'boils',
 'çıkık': 'dislocation',
 'çınla': 'ringing',
 'çiçek hastalık': 'smallpox',
 'çift görm': 'diplopia',
 'çift yumurta ik': 'fraternal twins',
 'çikolata kist': 'endometriosis',
 'çil': 'freckle',
 'Çocuk Acil Servisi': 'Paediatric A&E',
 'Çocuk Cerrahisi': 'Paediatric Surgery:',
 'Çocuk Doktoru': 'Paediatrician',
 'Çocuk ve Ergen Ruh Sağlığı ve Hastalıkları': 'Child and Adolescent Mental Health and Diseases',
 'çoklu organ yetmezlik': 'multiple organ failure',
 'çok yüksek klinik risk alt': 'clinically extremely vulnerable',
 'çölyak hastalık': 'Coeliac disease',
 'çürük': 'decay',
 'Dahiliye': 'Internal Medicine',
 'dalak': 'spleen',
 'damar': 'vein',
 'damar sertlik': 'artherosclerosis',
 'damar yolu açmak': 'establish vascular access',
 'damlacık': 'aerosol',
 'Dang humm': 'Dengue fever',
 'deli dan': 'CJD',
 'deli dana hastalık': 'Creutzfeldt-Jakob disease (CJD)',
 'demans': 'dementia',
 'depreşmek': 'recur',
 'deri al': 'hypodermic',
 'derin ven tromboz': 'deep vein thrombosis',
 'dermatit': 'dermatitis',
 'dermatolog': 'dermatologist',
 'detoks yapmak': 'detox',
 'dış gebelik': 'ectopic pregnancy',
 'dış kulak': 'auris extra',
 'difter': 'diphteria',
 'dikiş': 'sutures',
 'dikişleri almak': 'remove the sutures',
 'dikkat bozukluk': 'attention deficit disorder',
 'dikkat dağınıklık': 'distractability',
 'dikkat eksikliği ve hiperaktivite bozukluk': 'attention deficit hyperactivity disorder (ADHD)',
 'dispanser': 'dispensary',
 'displazi': 'dysplasia',
 'Diş ağr': 'toothache',
 'diş apse': 'dental abscess',
 'diş hek': 'dentist',
 'diş kemik': 'dentine',
 'diş kök': 'root',
 'diş mine': 'enamel',
 'diş tel': 'brace',
 'dişeti çekil': 'gum disease',
 'diür': 'diuretic',
 'diyet': 'diet',
 'doğumev': 'maternity hospital',
 'doğum kontrol hap': '"the pill"',
 'doğum kontrol yönte': 'contraceptives',
 'doğum kontrolü': 'contraception',
 'doğum lek': 'birthmark',
 'doğum servis': 'maternity ward',
 'doğum sonrası depresyon': 'postnatal depression',
 'doğuştan kalp hastalık': 'congenital heart disease',
 'doğuştan kalça çıkık': 'congenital hip dislocation',
 'doğuştan kalp rahatsızlık': 'congenital heart disease',
 'doku nakli': 'transplant',
 'dolg': 'filling',
 'domuz grip': 'swine flu',
 'dose': 'dose',
 'doygunluk': 'saturation',
 'dozaj': 'dosage',
 'dök': 'rash',
 'dölyo': 'vagina',
 'duyg': 'mood',
 'duyu bütünle': 'sensory integration',
 'duyu organ': 'sense organs',
 'düşük düzey': 'low-level',
 'düşük kan şeker': 'hypoglicemia',
 'düşük tansiyon': 'low blood pressure',
 'düşük yapmak': 'miscarry',
 'düztaban': 'flatfooted',
 'ebol': 'ebola',
 'ekl': 'joint',
 'eklem romatizma': 'rheumatoid arthritis',
 'e-nabız': 'electronic health registry system (E-pulse)',
 'eczaç': 'dispensing chemist',
 'edilgen bağışıklık': 'passive immunity',
 'eğriyi düzleştir': 'flatten the curve',
 'egzers': 'exercise',
 'eklem ağrı': 'joint pain',
 'ekokardiyogr': 'echocardiogram (ECG)',
 'ekspektoran': 'expectorant',
 'ekstübe etmek': 'extubate',
 'el ayak ağız hastalık': 'hand, foot and mouth disease',
 'elektrokardiyogr': 'electrocardiogram',
 'elektrolit': 'electrolytes',
 'elektroterapi': 'electrotherapy',
 'el hijyen': 'hand hygiene',
 'elle muayene etmek': 'palpate',
 'elle tedavi': 'chiropractice',
 'endokard': 'endocardium',
 'endokrinoloji': 'endocrinology',
 'endometriozis': 'endometriosis',
 'engel': 'disabled',
 'enjeksiyon': 'injection',
 'entübe etmek': 'intubate',
 'epidemiyolog': 'epidemiologist',
 'epileps': 'epilepsy',
 'estetik cerrahi': 'plastic surgery',
 'eşdeğer ilaç': 'generic drugs',
 'eştan': 'comorbidity',
 'faranjit': 'pharyngitis',
 'Favipiravir': 'Favipiravir',
 'felç': 'stroke',
 'fibroid': 'fibroid',
 'fibromiyalji': 'fibromyalgia',
 'filyasyon (saha incelemesi)': 'filiation',
 'fizik tedavi': 'physiotherapy',
 'fizyoterapi': 'physiotherapy',
 'fı': 'hernia',
 'freng': 'syphilis',
 'gaita': 'faeces',
 'gaita kaçır': 'fecal incontinence',
 'gangliyon': 'ganglion',
 'gastroenterit (bağırsak enfeksiyonu)': 'gastroenteritis',
 'gastroenterolog': 'gastroenterologist',
 'Gastroözofageal reflü hastalık': 'gastro-oesophageal reflux disease (GORD)',
 'gaz': 'flatulence',
 'gazlı bez': 'gauze',
 'genel sağlık muayen': 'check-up',
 'genital uçuk': 'genital herpes',
 'geniz et': 'adenoid',
 'giardiyazis': 'giardiasis',
 'gırtlak kanser': 'laryngeal cancer',
 'glisemik index': 'glysemic index (GI)',
 'glokom': 'glaucoma',
 'göğüs hastalık': 'pulmanory diseases',
 'göz ak': 'sclera',
 'göz damla': 'eye drops',
 'göz hek': 'ophthalmologist',
 'göz nezl': 'conjunctivitis',
 'göz tansiyon': 'glaucoma',
 'grip': 'flu',
 'guatr': 'goiter',
 'gül hastalık': 'rosacea',
 'günde iki kez': 'B.I.D.',
 'hafıza kayp': 'amnesia',
 'hafıza tepki': 'memory response',
 'hakem': 'peer-reviewed',
 'halk sağlık': 'public health',
 'hamilelik': 'pregnancy',
 'hantavirüs': 'hantavirus',
 'hap': 'pill',
 'hapşırmak': 'sneeze',
 'hastalığın gidişat öngör': 'prognosis',
 'hastalık': 'disease',
 'hastalık görülüş sıklık': 'incidence',
 'hastalık oluştur': 'virulence',
 'hatırlatma aşıs': 'booster vaccine',
 'havalan': 'ventilate',
 'havale geçirmek': 'suffer a seizure',
 'hayvandan insana bulaş': 'zoonosis',
 'hazımsızlık': 'Indigestion',
 'hek': 'physician',
 'hematoloji': 'hematology',
 'hemoli': 'hemolytic',
 'hemolitik üremik sendrom': 'hemolytic uremic syndrome',
 'hemoroid': 'haemorrhoids',
 'hepatit': 'hepatitis',
 'heyet rapor': 'medical council report',
 'Hıfzıssıhha': 'public hygiene',
 'hıyarcıklı veba': 'bubonic plague',
 'Hızlı Antijen Testi': 'Lateral Flow Test',
 'hidroterapi': 'hydrotherapy',
 'hiperg': 'hyperglicemia',
 'hiperhidroz': 'hyperhidrosis',
 'hipermetropluk': 'hypermetropia',
 'hipertiroid': 'hyperthyroid',
 'hipofiz bezine illişk': 'pituitary',
 'hipoglise': 'hypoglicemia',
 'hipotalamus': 'hypothalamus',
 'hormon bastırıç': 'hormone suppressant',
 'Hudut ve Sahiller Sağlık Genel Müdürlüğü': 'General Directorate of Health for Borders and Coasts',
 'huzursuz bacak sendrom': 'restless legs syndrome',
 'huzursuz bağırsak sendrom': 'Irritable bowel syndrome (IBS)',
 'iç kulak': 'labyrinth',
 'iç kulak iltihap': 'otitis interna',
 'idrar kaçır': 'incontinence',
 'idrar örnek': 'urine sample',
 'idrar yolu enfeksiyon': 'urinary tract infection',
 'iğn': 'injection',
 'iktidarsızlık': 'impotence',
 'ilerleyiç': 'progressive',
 'ilk müdahale sağlık ekip': 'paramedics',
 'iltihap': 'inflamed',
 'immunosupresan': 'immunosuppressant',
 'immünsupresif': 'immunosuppressive',
 'implant': 'implant',
 'ince bağır': 'small intestines',
 'infer': 'infertility',
 'inflamasyon': 'inflammation',
 'inm': 'stroke',
 'intihar': 'suicide',
 'intihara meyil': 'suicidal',
 'irs': 'inherited',
 'ishal': 'diarrhoea',
 'işitme engellilik': 'deafness',
 'işitme kayp': 'hearing loss',
 'İYE': 'UTI',
 'iyi huyl': 'benign',
 'iyileş': 'heal',
 'jenerik ilaç': 'generic drug',
 'jinekolog': 'gynecologist',
 'jinekoloji': 'gynecology',
 'kaba et': 'buttocks',
 'kabakulak': 'mumps',
 'kabızlık': 'constipation',
 'kabuk bağlamak': 'scab over /scab',
 'kadın doğum doktor': 'gynecologist',
 'kadın sünn': 'female genital mutilation (FGM)',
 'kalın bağır': 'colon',
 'kalın bağırsak ve rektum kanser': 'colon and rectal cancer',
 'kalıtsal': 'hereditary',
 'kalp ağr': 'heartache',
 'kalp damar madde': 'cardiovascular agents',
 'kalp yetmezlik': 'heart failure',
 'kamburluk': 'ankylosing spondylitis',
 'kan bil': 'hematology',
 'kan grup': 'blood type',
 'kan kanser': 'leukemia',
 'kan nakli': 'blood transfusion',
 'kan örnek': 'blood sample',
 'kan pulcuk': 'thrombocyte',
 'kanserojen': 'carcinogenic',
 'kan şekeri düzenleyiç': 'blood sugar regulators',
 'kan sulandırıç': 'anti-coagulants',
 'kan zehirlenme': 'blood poisoning',
 'kan': 'bleeding',
 'kanser': 'cancer',
 'kansızlık': 'anemia',
 'kapan': 'lockdown',
 'kapl': 'veneer',
 'kapsül': 'capsule',
 'karaciğer kanser': 'liver cancer',
 'karaciğer yağlanma': 'fatty liver',
 'kardiyolog': 'cardiologist',
 'kardiyovasküler ajan': 'cardiovascular agents',
 'kar': 'abdomen',
 'karıncık': 'vetricule',
 'kasılmayı önleyiç': 'anticonvulsants',
 'kaş': 'itch',
 'katar': 'catarrh',
 'katarakt': 'cataract',
 'kaygı bozukluk': 'anxiety disorder',
 'kayropraktik': 'chiropractic',
 'KBB': 'ENT',
 'kelebek hastalık': 'epidermolysis bullos',
 'kemik erime': 'osteoporosis',
 'kemik ilik': 'bone marrow',
 'kemik kanser': 'bone cancer',
 'kendi kendine karantina': 'self-isolation',
 'kendi kendini karantina altına almak': 'self isolate',
 'ken': 'tick',
 'kesik': 'cut',
 'kesik ve sıyrık': 'cuts and grazes',
 'kesk': 'sharp',
 'kıkırdak': 'cartilage',
 'kıl dönm': 'pilonidal sinus',
 'kıl kurt': 'pinworm',
 'kılcal damar': 'capillary',
 'kırık': 'fracture',
 'kısır': 'sterile',
 'kısırlık': 'infertility',
 'kızamık': 'measles',
 'kızamıkçık': 'German measles',
 'kızıl hastalık': 'scarlet fever',
 'kızlık zar': 'hymen',
 'kireçlen': 'arthritis',
 'kistik fibrozis': 'cystic fibrosis',
 'kişilik bozukluk': 'personality disorder',
 'kişisel koruyucu ekipman': 'personal protection equipment',
 'kişisel sağlık kayt': 'personal health registry',
 'KKE': 'PPE',
 'klamidya': 'chlamydia',
 'klinik kimya': 'clinical chemistry',
 'koğuş': 'ward',
 'koli basi': 'E.coli',
 'kolit': 'colitis',
 'koltuk değnek': 'crutches',
 'komaya girmek': 'slip into coma',
 'komorbi': 'comorbidity',
 'konak': 'cradle cap',
 'konjenital': 'congenital',
 'konjonktivit': 'conjunctivitis',
 'kornea': 'cornea',
 'koruyucu sağlık hizmet': 'preventive health services',
 'kostokondrit': 'costochondritis',
 'köpek diş': 'canine',
 'köpr': 'dental crown',
 'köprücük kemik': 'collar bone',
 'kö': 'cripple',
 'kötüye gitmek': 'deteriorate',
 'kriyoterapi': 'cryotheraphy',
 'kronik': 'chronic',
 'krup': 'croup',
 'kut': 'rabies',
 'kulak ağrı': 'earache',
 'kulak burun boğaz': 'ENT',
 'kulak çınla': 'tinnitus',
 'kulak kir': 'earvax',
 'kulak salyangoz': 'cochlea',
 'kulak zar': 'membrana tympanica',
 'kulakçık': 'atrium',
 'kuluçka süre': 'incubation period',
 'kurdeşen': 'urticaria',
 'kuşpalaz': 'diphteria',
 'kusmayı önleyiç': 'antiemetic',
 'kuyruk sok': 'coccyx',
 'künt': 'blunt',
 'künt ağr': 'dull pain',
 'kürek kemik': 'scapula',
 'küresel salg': 'global pandemic',
 'laranjit': 'laryngytis',
 'lavaj yapmak': 'enema',
 'lazerli tedavi': 'laser therapy',
 'leğen boşluk': 'pelvis',
 'leğen kemik': 'hipbone',
 'lenf': 'lymph',
 'lenf kanser': 'lymphoma',
 'lifli tümör': 'fibroid',
 'lös': 'leukemia',
 'madde bağımlılık': 'substance abuse',
 'madde bak': 'addict',
 'makat': 'anus',
 'makula dejenerasyon': 'macular degeneration',
 'mantar enfeksiyon': 'thrush',
 'mantar giderici ilaç': 'antifungals',
 'manuel terapi': 'chiropractic',
 'manüpilatif tedavi': 'chiropractic',
 'maske kullan': 'mask wearing',
 'MR': 'MRI',
 'Manyetik Rezonans (MR)': 'MRI (Magnetic resonance imaging)',
 'maymun çiçek': 'monkeypox',
 'melanom': 'melanoma',
 'meme kanser': 'breast cancer',
 'menenjit': 'meningitis',
 'Meniere hastalık': "Meniere's disease",
 'Meningokok menenjit': 'meningococcal meningitis',
 'mercek': 'lens',
 'merh': 'ointment',
 'MERS': 'MERS',
 'mesafeyi kor': 'physical distancing',
 'mesane': 'bladder',
 'mesane kanser': 'bladder cancer',
 'mide fı': 'hiatus hernia',
 'mide kanser': 'gastric cancer',
 'mide özsu': 'gastric juice',
 'mide-bağırsak yang': 'gastroenteritis',
 'mikrobiyoloji': 'microbiology',
 'mikrop': 'septic',
 'miyokard': 'myocardium',
 'miyopluk': 'myopia',
 'moleküler biyoloji': 'molecular biology',
 'moral bozukluk': 'low mood',
 'motor nöron hastalık': 'motor neurone diseases',
 'MR çek': 'have a MRI scan',
 'muayen': 'examination',
 'muayene saat': 'surgery hours',
 'multipl skleroz': 'multiple sclerosis',
 'nap': 'pulse',
 'nabız ölçmek': 'take the pulse',
 'nadir hastalık': 'rare diseases',
 'nakil': 'transplant',
 'narkoz vermek': 'anaesthetize',
 'nasır': 'callus',
 'nazofarenks kanser': 'nasopharyngeal cancer',
 'nefes darlık': 'shortness of breath',
 'nekahet': 'convalescence',
 'neşter': 'scalpel',
 'nezl': 'common cold',
 'nezle olmak': 'catch a cold',
 'Non-Hodgkin Lenfoma': 'Non-Hodgkin Lymphoma',
 'Nonsteroid Antienflamatuar ilaç': 'non-steroidal anti-inflammatory drugs (NSAIDs)',
 'norovirüs': 'norovirus',
 'nörovirüs': 'norovirus',
 'normalleşm': 'normalization',
 'nöbet': 'episode',
 'nöroblastom': 'neuroblastoma',
 'nörodejeneratif': 'neuro-degenerative',
 'nöroloji': 'neurology',
 'nöron': 'neuron',
 'nöropatik ağr': 'neuropathic pain',
 'NSAİ': 'NSAIDs',
 'numuler egzema': 'discoid eczema',
 'nüzul': 'stroke',
 'obez': 'obesity',
 'obsesif kompulsif bozukluk': 'obsessive compulsive disorder',
 'oftalmik implant': 'ophthalmic implants',
 'OKD': 'OCD',
 'oksimetr': 'oximeter',
 'Omicron': 'Omicron',
 'omurg': 'vertebral column',
 'omurga eğrilik': 'scoliosis',
 'omur': 'vertebrae',
 'onikiparmak bağır': 'duodenum',
 'onkoloji': 'oncology',
 'orak hücre anem': 'sickle cell disease',
 'orta kulak': 'middle ear',
 'orta kulak iltihap': 'otitis media',
 'ortopedi uzman': 'orthopedist',
 'Ortopedi ve Travmatoloji': 'Orthopedics and Traumatology',
 'OSD': 'ASD',
 'osteoartrit': 'osteoarthritis',
 'osteoporoz': 'osteoporosis',
 'otistik spektrum bozukluk': 'autistic spectrum disorder (ASD)',
 'otoimmü': 'autoimmune',
 'over': 'ovary',
 'ödyo': 'bile duct',
 'öğürmek': 'retch',
 'öğür': 'retching',
 'öksürük': 'cough',
 'ölü dok': 'stillbirth',
 'ölümcül': 'terminal',
 'öpücük hastalık': 'glandular fever',
 'örs kemik': 'incus',
 'östaki bor': 'tuba auditiva',
 'öykü': 'story',
 'özkı': 'suicide',
 'özofagus kanser': 'oesophageal cancer',
 'pamukçuk': 'oral thrush',
 'pandem': 'pandemic',
 'panik bozukluk': 'panic disorder',
 'pankreas kanser': 'pancreatic cancer',
 'pansuman': 'dressing',
 'pansuman yapmak': 'dress',
 'parçalı kırık': 'segmental fracture',
 'Parkinson hastalık': "Parkinson's disease",
 'pekiştirme aşıs': 'booster vaccine',
 'peklik': 'constipation',
 'pelvis': 'pelvis',
 'penis kanser': 'penile cancer',
 'periferal nöropati': 'peripheral neuropathy',
 'perikard': 'pericardium',
 'pernio': 'chilblains',
 'pıhtılaş': 'clotting',
 'Pnömokokal menenjit': 'pneumococcal meningitis',
 'polip': 'polyp',
 'preeklampsi': 'pre-eclampsia',
 'prognoz': 'prognosis',
 'prostat kanser': 'prostate cancer',
 'psikanaliz': 'psychoanalysis',
 'psikoterapi': 'psychotherapy',
 'psikotik epizod': 'psychotic episode',
 'psikoz': 'psychosis',
 'PTSD': 'PTSD',
 'pulmoner fibroz': 'idiopathic pulmonary fibrosis',
 'pulmoner fibrozis': 'idiopathic pulmonary fibrosis',
 'R değer': 'R number',
 'radyolog': 'radiologist',
 'rahatsızlık': 'illness',
 'rahim ağz': 'cervix',
 'rahim ağzı kanser': 'cervical cancer',
 'rahim kanser': 'endometrial cancer',
 'randevu al': 'appointment',
 'reç': 'prescription',
 'reçeteli ilaç': 'prescription pill',
 'reçetes': 'over the counter',
 'regl': 'period',
 'regl olmak': 'have a period',
 'reseptör': 'receptor',
 'retina': 'retina',
 'retinoblastom': 'retinoblastoma',
 'revir': 'sick berth',
 'Rift Valley Fever': 'Rift Vadisi Ateşi',
 'ritim bozukluk': 'arrythmia',
 'romatizma': 'rheumatism',
 'romatoid artrit': 'rheumatoid arthritis',
 'röntgen': 'X-ray',
 'röntgen uzman': 'radiographer',
 'Ruh Sağlığı ve Hastalıkları': 'Mental Health and Diseases',
 'saç kök': 'follicle',
 'saçkıran': 'alopecia',
 'safra kan': 'bile duct',
 'safra kesesi iltihap': 'cholecystitis',
 'safra kesesi taş': 'gall stone',
 'safra kesesinin alın': 'cholecystectomy',
 'sağlık': 'healthy',
 'sağlık nefer': 'health conscript',
 'sağlık ocak': 'community clinic',
 'sağlık persone': 'medical staff',
 'sağlık rapor': 'medical certificate',
 'sağlık sigor': 'medical insurance',
 'sakatlan': 'suffer an injury',
 'sakinleştiriç': 'tranquilizer',
 'salg': 'epidemic',
 'salgın hastalıklar uzman': 'epidemiologist',
 'saman nezl': 'hay fever',
 'sanr': 'hallucination',
 'sara hastalık': 'epilepsy',
 'sarı nokta hastalık': 'macular degeneration',
 'sarıhumm': 'yellow fever',
 'sarılık': 'jaundice',
 'sarkom': 'sarcoma',
 'SARS': 'SARS',
 'satürasyon': 'saturation',
 'seçici serotonin gerialım inhibitör': 'selective seratonin reuptake inhibitors',
 'sedef hastalık': 'psoriasis',
 'sedye': 'stretcher',
 'sel': 'benign',
 'selülit': 'cellulitis',
 'sepsis': 'sepsis',
 'serebral palsi': 'cerebral palsy',
 'seroloji': 'serology',
 'sertleşme bozukluk': 'erectile dysfunction',
 'serum': 'drip',
 'sıhhat': 'health',
 'sıhhatli': 'healthy',
 'sidikyo': 'urethra',
 'siğil': 'verruca',
 'sinir ağr': 'neuropathic pain',
 'sinir bağlan': 'synapsis',
 'sinir dük': 'ganglion',
 'sinir göz': 'neuron',
 'sinir kavşak': 'synapse',
 'sinüzit': 'sinusitis',
 'siroz': 'cirrhosis',
 'sistit': 'cystitis',
 'sivil': 'acne',
 'siyatik': 'sciatica',
 'sıtm': 'malaria',
 'skolyoz': 'scoliosis',
 'smear test': 'smear test',
 'soğuk algınlık': 'cold',
 'soğuk yaralan': 'chilblains',
 'soğukla sağal': 'cryotheraphy',
 'solucan': 'worm',
 'solunum cihaz': 'ventilator',
 'solunum cihazından ayırmak': 'extubate',
 'Spinal Kas Atrofisi': 'Spinal Muscular Atrophy',
 'SSRI': 'SSRI',
 'stent takıl': 'stent insertion',
 'su kayp': 'dehydration',
 'suçiçek': 'chickenpox',
 'suş': 'strain',
 'su toplamış kabarcık': 'blister',
 'süper bulaştırıç': 'super spreader',
 'sürekli öksürük': 'continous cough',
 'sür': 'swab',
 'şaşılık': 'squint',
 'şizofren': 'schizophrenia',
 'şeker hastalık': 'diabetes',
 'şırıng': 'syringe',
 'şişkinlik': 'flatulence',
 'şişlik': 'bump',
 'şurup': 'syrup',
 'tahta kur': 'bedbug',
 'takip': 'trace',
 'takma diş': 'denture',
 'tam kan say': 'CBC',
 'tan': 'diagnosis',
 'tanı koymak': 'diagnose',
 'tansiyon': 'blood pressure',
 'tarama test': 'screening test',
 'taşikardi': 'tachycardia',
 'tatlandırıç': 'sweetener',
 'tavşan dudak': 'cleft lip',
 'tavuk kar': 'retinitis pigmentosa',
 'tedavi etmek': 'treat',
 'tek yumurta ik': 'identical twins',
 'tekerlekli sandalye': 'wheelchair',
 'temaslı kiş': 'close contact',
 'temastan korun': 'shielding',
 'tenya': 'tapeworm',
 'teşhis': 'diagnosis',
 'testis kanser': 'testicular cancer',
 'tetanoz': 'tetanus',
 'tıbbi cihaz': 'medical devices',
 'tıbbi mümessil': 'medical representative',
 'tıp': 'medicine',
 'tıp doktor': 'MD',
 'tırnak batm': 'ingrown toenail',
 'tırnak mantar': 'fungal nail infection',
 'tifo': 'spotted fever',
 'tiroid bez': 'thyroidea',
 'tiroid kanser': 'thyroid cancer',
 'tiroid yetmezlik': 'hypothyroid',
 'tok karn': 'on a full stomach',
 'toksik şok sendrom': 'toxic shock syndrome',
 'toplum bağışıklık': 'herd immunity',
 'torasik': 'thoracic',
 'trav': 'trauma',
 'Travma Sonrası Stres Bozukluğu': 'Post-Traumatic Stress Disorder (PTSD)',
 'travma uzman': 'traumatologist',
 'trigeminal nevralji': 'trigeminal neuralgia',
 'trombosit': 'platelets',
 'tromboz': 'thrombosis',
 'tüberküloz': 'tuberculosis',
 'tuvalete çıkmak': 'have bowel movement',
 'tüylü hücreli lös': 'hairy cell leukaemia',
 'uçuk': 'cold sore',
 'uğul': 'whooshing',
 'ultrason': 'ultrasound',
 'ultrasonografi': 'ultrasound',
 'uyku apne': 'sleep apnea',
 'uyku bozukluk': 'sleep disorder',
 'uykusuzluk': 'Insomnia',
 'uyuş': 'numbness',
 'uyuşturuç': 'drugs',
 'uyuşturucu bağımlılık': 'drug abuse',
 'uyuşturucu ticare': 'drug trafficking',
 'uyuşuk': 'numb',
 'u': 'scabies',
 'üfür': 'murmur',
 'ürik asit': 'uric acid',
 'ürogenital yol enfeksiyon': 'genitourinary infection',
 'ürolog': 'urologist',
 'üroloji': 'urology',
 'üst deri tabaka': 'epidermis',
 'üst yutak kanser': 'nasopharyngeal cancer',
 'üzengi kemik': 'stapes',
 'vaka izolasyon': 'case isolation',
 'vajina': 'vagina',
 'veba': 'plague',
 'ver': 'TB',
 'verem savaş dispanser': 'tuberculosis dispensary',
 'vetrikül': 'vetricule',
 'viral hepatit': 'viral hepatitis',
 'virolog': 'virologist',
 'virüs uzman': 'virologist',
 'vitamin takvi': 'vitamin supplements',
 'vitiligo': 'vitiligo',
 'vücut kitle endeks': 'body mass index',
 'yang': 'inflammation',
 'yangı': 'inflamed',
 'yanık': 'burn',
 'yanlış katlan': 'misfolded',
 'yapay kom': 'medically-induced coma',
 'yar': 'wound',
 'yara bant': 'plaster',
 'yara ber': 'bruise',
 'yara iz': 'scar',
 'yarık dudak ve damak': 'cleft lip and palate',
 'yatak ıslatmak': 'bedwetting',
 'yatarak tedavi': 'inpatient treatment',
 'yaygın kaygı bozukluk': 'Generalized Anxiety Disorder (GAD)',
 'yaygınlık': 'prevalence',
 'yemek borusu kanser': 'esophageal cancer',
 'yenidoğan': 'newborn',
 'yenidoğan yoğun bak': 'neonatal incentive care unit (NICU)',
 'yerinden çık': 'dislocated',
 'yetersiz beslen': 'malnutrition',
 'yetim ilaç': 'orphan drugs',
 'yırtıl': 'tear',
 'Yoğun Bakım Ünitesi': 'Intensive Care Unit (ICU)',
 'yoksunluk': 'withdrawal',
 'yumurtalık': 'ovary',
 'yumurtalık kist': 'ovarian cyst',
 'yumuşak doku kanser': 'sarcoma',
 'yutma zorluk': 'dysphagia',
 'yüksek ateş': 'high temperature',
 'yüksek kan şeker': 'hyperglicemia',
 'yüksek tansiyon': 'high blood pressure',
 'zar çeper': 'membrane wall',
 'zatülcenp': 'pleurisy',
 'zatürr': 'pneumonia',
 'zehirli guatr': 'hyperthyroid',
 'zon': 'shingles (herpes zoster)',
 'zoonoz': 'zoonosis',
 'PROPN_Oral and Dental Health Centres': 'Ağız Diş Sağlığı Merkezleri',
 'PROPN_Family Health Centres': 'Aile Sağlığı Merkezleri',
 'PROPN_European Food Safety Authority': 'Avrupa Gıda Güvenliği Otoritesi',
 'PROPN_Child Adolescent Women and Reproductive Health Units': 'Çocuk Ergen Kadın ve Üreme Sağlığı Birimleri',
 'PROPN_State Hospitals': 'Devlet Hastaneleri',
 'PROPN_Dialysis Centres': 'Diyaliz Merkezleri',
 'PROPN_Chamber of Pharmacists ': 'Eczacı odası',
 'PROPN_Home Care Centres': 'Evde Bakım Merkezleri',
 'PROPN_Centres Providing Mobile OHS Services': 'Gezici İSG Hizmeti Veren Merkezler',
 'PROPN_Immigrant Health Centres': 'Göçmen Sağlığı Merkezleri',
 'PROPN_Public Health Laboratories': 'Halk Sağlığı Laboratuvarları',
 'PROPN_Public Hygiene Institute ': 'Hıfzıssıhha Enstitüsü',
 'PROPN_GD of Health for Borders and Coasts': 'Hudut Sahiller SGM',
 'PROPN_Hudut ve Sahiller Sağlık Genel Müdürlüğü': 'General Directorate of Health for Borders and Coasts',
 'PROPN_Medicines and Medical Devices Agency': 'İlaç ve Tıbbi Cihaz Kurumu',
 'PROPN_District Health Directorates': 'İlçe Sağlık Müdürlükleri',
 'PROPN_Hearing Aid Centres': 'İşitme Cihazı Merkezleri',
 'PROPN_Bespoke Prosthetics and Orthotics Centres': 'Ismarlama Protez ve Ortez Merkezleri',
 'PROPN_Blood Centres': 'Kan Merkezleri',
 'PROPN_Cancer Early Diagnosis, Screening and Education Centres': 'KETEM',
 'PROPN_Opticians': 'Optisyenlik Müesseseleri',
 'PROPN_Organ and Tissue Transplant Centres': 'Organ ve Doku Nakli Merkezleri',
 'PROPN_Private Hospitals': 'Özel Hastaneler',
 'PROPN_Private Diagnosis and Treatment Centres': 'Özel Teşhis ve Tedavi Merkezleri',
 'PROPN_Psychotechnical Centres': 'Psikoteknik Merkezleri',
 'PROPN_surgeon general office': 'Sağlık Dairesi Başkanlığı',
 'PROPN_Healthy Eating and Obesity Counseling Unit ': 'Sağlıklı Beslenme ve Obezite Danışma Birimi',
 'PROPN_Turkish Medicines and Medical Devices Agency': 'TİTCK ',
 'PROPN_Community Mental Health Centres': 'Toplum Ruh Sağlığı Merkezleri',
 'PROPN_Community Health Centres': 'Toplum Sağlığı Merkezleri',
 'PROPN_Turkish Medical Associaton': 'Türk Tabipleri Birliği',
 'PROPN_Scientific and Technological Research Council of Turkey': 'Türkiye Bilimsel ve Teknolojik Araştırma Kurumu',
 'PROPN_Turkish Statistical Institute': 'TÜİK',
 'PROPN_Turkish Statistical Institute (TÜİK)': 'Türkiye İstatistik Kurumu',
 'PROPN_Health Institutes of Turkey': 'TÜSEB',
 'PROPN_Turkish Health Care Quality and Accreditation Institute (TÜSKA)': 'Türkiye Sağlık Hizmetleri Kalite ve Akreditasyon Enstitüsü',
 'PROPN_Turkish Health Care Quality and Accreditation Institute': 'TÜSKA',
 'PROPN_Tuberculosis Control Dispensary': 'Verem Savaş Dispanserleri',
 'PROPN_Abbott': 'Abbott',
 'PROPN_AbbVie ': 'AbbVie ',
 'PROPN_Alkem ': 'Alkem ',
 'PROPN_Amgen ': 'Amgen ',
 'PROPN_Astellas': 'Astellas',
 'PROPN_Astrazeneca': 'Astrazeneca',
 'PROPN_Bausch': 'Bausch',
 'PROPN_Bayer': 'Bayer',
 'PROPN_BeiGene ': 'BeiGene ',
 'PROPN_Biocon': 'Biocon',
 'PROPN_Biogen': 'Biogen',
 'PROPN_BioNTech': 'BioNTech',
 'PROPN_Bristol Myers Squibb': 'Bristol Myers Squibb',
 'PROPN_Chugai': 'Chugai',
 'PROPN_Cipla': 'Cipla',
 'PROPN_CRISPR': 'CRISPR',
 'PROPN_CSL': 'CSL',
 'PROPN_CVS Health ': 'CVS Health ',
 'PROPN_Eli Lilly': 'Eli Lilly',
 'PROPN_Exelixis': 'Exelixis',
 'PROPN_Gilead': 'Gilead',
 'PROPN_Gingko Bioworks': 'Gingko Bioworks',
 'PROPN_GlaxoSmithKline ': 'GlaxoSmithKline ',
 'PROPN_Jiangsu Hengrui': 'Jiangsu Hengrui',
 'PROPN_Johnson & Johnson ': 'Johnson & Johnson ',
 'PROPN_Kobayashi': 'Kobayashi',
 'PROPN_Lonza': 'Lonza',
 'PROPN_Lupin ': 'Lupin ',
 'PROPN_Merck ': 'Merck ',
 'PROPN_Moderna': 'Moderna',
 'PROPN_Nippon Shinyaku': 'Nippon Shinyaku',
 'PROPN_Novartis ': 'Novartis ',
 'PROPN_Novavax': 'Novavax',
 'PROPN_Novo Nordisk': 'Novo Nordisk',
 'PROPN_Pfizer ': 'Pfizer ',
 'PROPN_Regeneron ': 'Regeneron ',
 'PROPN_Roche ': 'Roche ',
 'PROPN_Sanofi ': 'Sanofi ',
 'PROPN_Sino': 'Sino',
 'PROPN_Sun Pharmaceutical': 'Sun Pharmaceutical',
 'PROPN_Takeda': 'Takeda',
 'PROPN_Teva': 'Teva',
 'PROPN_Vertex': 'Vertex',
 'PROPN_Vifor': 'Vifor',
 'PROPN_Walgreens Boots': 'Walgreens Boots',
 'PROPN_West Pharma': 'West Pharma',
 'PROPN_WuXi': 'WuXi',
 'PROPN_Zoetis': 'Zoetis',
 'PROPN_Abdi İbrahim  ': 'Abdi İbrahim  ',
 'PROPN_Adeka ': 'Adeka ',
 'PROPN_Ali Raif İlaç': 'Ali Raif İlaç',
 'PROPN_Argis ': 'Argis ',
 'PROPN_Arion ': 'Arion ',
 'PROPN_Arven İlaç': 'Arven İlaç',
 'PROPN_Atabay Kimya  ': 'Atabay Kimya  ',
 'PROPN_Berko İlaç ': 'Berko İlaç ',
 'PROPN_Bilim İlaç ': 'Bilim İlaç ',
 'PROPN_Biofarma ': 'Biofarma ',
 'PROPN_Deva ': 'Deva ',
 'PROPN_Era Pharma ': 'Era Pharma ',
 'PROPN_Farmatek ': 'Farmatek ',
 'PROPN_Gen İlaç ': 'Gen İlaç ',
 'PROPN_Gensenta': 'Gensenta',
 'PROPN_İ. E. Ulagay İlaç ': 'İ. E. Ulagay İlaç ',
 'PROPN_İlko İlaç ': 'İlko İlaç ',
 'PROPN_Koçak Farma': 'Koçak Farma',
 'PROPN_Kurtsan ': 'Kurtsan ',
 'PROPN_MS Pharma ': 'MS Pharma ',
 'PROPN_Nobel ': 'Nobel ',
 'PROPN_Onko ': 'Onko ',
 'PROPN_Pharmactive': 'Pharmactive',
 'PROPN_Polifarma': 'Polifarma',
 'PROPN_Sanofi': 'Sanofi',
 'PROPN_Sanovel': 'Sanovel',
 'PROPN_Santa Farma': 'Santa Farma',
 'PROPN_Teknovet': 'Teknovet',
 'PROPN_Tüm-Ekip': 'Tüm-Ekip',
 'PROPN_Turgut İlaçları': 'Turgut İlaçları',
 'PROPN_Turktıpsan': 'Turktıpsan',
 'PROPN_Ulkar Kimya': 'Ulkar Kimya',
 'PROPN_Vefa İlaç': 'Vefa İlaç',
 'PROPN_Vem İlaç': 'Vem İlaç',
 'PROPN_Zade Vital ': 'Zade Vital ',
 'PROPN_Acıbadem ': 'Acıbadem ',
 'PROPN_Avcılar ': 'Avcılar ',
 'PROPN_Avicenna ': 'Avicenna ',
 'PROPN_Liv Hospital': 'Liv Hospital',
 'PROPN_Lokman Hekim': 'Lokman Hekim',
 'PROPN_Medical Park': 'Medical Park',
 'PROPN_Medicana ': 'Medicana ',
 'PROPN_Memorial ': 'Memorial ',
 'PROPN_Moodist': 'Moodist',
 'PROPN_Vizyon': 'Vizyon',
 'PROPN_head lice': 'bit',
 'PROPN_EKG / ECG': 'EKG ',
 'PROPN_Ağız Diş Sağlığı Merkezleri': 'Oral and Dental Health Centres',
 'PROPN_Aile Sağlığı Merkezleri': 'Family Health Centres',
 'PROPN_Çocuk Ergen Kadın ve Üreme Sağlığı Birimleri': 'Child Adolescent Women and Reproductive Health Units',
 'PROPN_Devlet Hastaneleri': 'State Hospitals',
 'PROPN_Diyaliz Merkezleri': 'Dialysis Centres',
 'PROPN_Eczacı odası': 'Chamber of Pharmacists ',
 'PROPN_Evde Bakım Merkezleri': 'Home Care Centres',
 'PROPN_Gezici İSG Hizmeti Veren Merkezler': 'Centres Providing Mobile OHS Services',
 'PROPN_Göçmen Sağlığı Merkezleri': 'Immigrant Health Centres',
 'PROPN_Halk Sağlığı Laboratuvarları': 'Public Health Laboratories',
 'PROPN_Hıfzıssıhha Enstitüsü': 'Public Hygiene Institute ',
 'PROPN_Hudut Sahiller SGM': 'GD of Health for Borders and Coasts',
 'PROPN_İlaç ve Tıbbi Cihaz Kurumu': 'Medicines and Medical Devices Agency',
 'PROPN_İlçe Sağlık Müdürlükleri': 'District Health Directorates',
 'PROPN_İşitme Cihazı Merkezleri': 'Hearing Aid Centres',
 'PROPN_Ismarlama Protez ve Ortez Merkezleri': 'Bespoke Prosthetics and Orthotics Centres',
 'PROPN_Kan Merkezleri': 'Blood Centres',
 'PROPN_Kanser Erken Teşhis Tarama ve Eğitim Merkezleri ': 'Cancer Early Diagnosis, Screening and Education Centres',
 'PROPN_KETEM': 'Cancer Early Diagnosis, Screening and Education Centres',
 'PROPN_Optisyenlik Müesseseleri': 'Opticians',
 'PROPN_Organ ve Doku Nakli Merkezleri': 'Organ and Tissue Transplant Centres',
 'PROPN_Özel Hastaneler': 'Private Hospitals',
 'PROPN_Özel Teşhis ve Tedavi Merkezleri': 'Private Diagnosis and Treatment Centres',
 'PROPN_Psikoteknik Merkezleri': 'Psychotechnical Centres',
 'PROPN_Sağlık Dairesi Başkanlığı': 'surgeon general office',
 'PROPN_Sağlıklı Beslenme ve Obezite Danışma Birimi': 'Healthy Eating and Obesity Counseling Unit ',
 'PROPN_TİTCK ': 'Turkish Medicines and Medical Devices Agency',
 'PROPN_Toplum Ruh Sağlığı Merkezleri': 'Community Mental Health Centres',
 'PROPN_Toplum Sağlığı Merkezleri': 'Community Health Centres',
 'PROPN_TTB': 'Turkish Medical Associaton',
 'PROPN_TÜBİTAK': 'Scientific and Technological Research Council of Turkey',
 'PROPN_TÜİK': 'Turkish Statistical Institute',
 'PROPN_Türk Tabipleri Birliği': 'Turkish Medical Associaton',
 'PROPN_Türkiye Bilimsel ve Teknolojik Araştırma Kurumu': 'Scientific and Technological Research Council of Turkey',
 'PROPN_Türkiye İstatistik Kurumu': 'Turkish Statistical Institute (TÜİK)',
 'PROPN_Türkiye Sağlık Enstitüleri Başkanlığı': 'Health Institutes of Turkey',
 'PROPN_Türkiye Sağlık Hizmetleri Kalite ve Akreditasyon Enstitüsü': 'Turkish Health Care Quality and Accreditation Institute (TÜSKA)',
 'PROPN_TÜSEB': 'Health Institutes of Turkey',
 'PROPN_TÜSKA': 'Turkish Health Care Quality and Accreditation Institute',
 'PROPN_Verem Savaş Dispanserleri': 'Tuberculosis Control Dispensary',
 'PROPN_pire': 'louse',
 'PROPN_üre': 'urea'}
